<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc91f9d8a2f27eb3e0d3972d31ca8b8bc
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc91f9d8a2f27eb3e0d3972d31ca8b8bc::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc91f9d8a2f27eb3e0d3972d31ca8b8bc::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc91f9d8a2f27eb3e0d3972d31ca8b8bc::$classMap;

        }, null, ClassLoader::class);
    }
}
